# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  acr: cbacrkk

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Api.BoarService/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Bartek-MPN'
        azureContainerRegistry: $(acr)
        dockerComposeFile: 'docker-compose.yml'
        action: 'Build services'
        qualifyImageNames: true
        additionalImageTags: $(Build.BuildId)
    - pwsh: |
        docker images ls

