version: '3.4'

services:
  web.frontend:
    container_name: web.frontend
    image: cbacrkk.azurecr.io/webfrontend
    build:
      context: .
      dockerfile: Web.Frontend/Dockerfile
    depends_on:
        - api.foodservice
        - api.boarservice

  api.foodservice:
    container_name: api.foodservice
    image: cbacrkk.azurecr.io/apifoodservice
    build:
      context: .
      dockerfile: Api.FoodService/Dockerfile

  api.boarservice:
    container_name: api.boarservice
    image: cbacrkk.azurecr.io/apiboarservice
    build:
      context: .
      dockerfile: Api.BoarService/Dockerfile